### ISSUE TITLE
`make` step fails when building with documentation

### ISSUE THREAD

**Issue by maxim-belkin** [intel/libva#239]
Hi! I'm seeing the following error message when trying to build `libva` with documentation,
```
Making all in doc
make[2]: Entering directory '/tmp/libva-20180919-53586-1g8vt3z/libva-2.2.0/doc'
make[2]: *** No rule to make target '../doc/va_footer.html', needed by 'Doxyfile'.  Stop.
```

**Comment by Corin-EU** [comment]
Presumably you were attempting a build of libva from the 2.3.0 tar archive.

The file doc/va_footer.html is not present in the libva 2.3.0 tar archive.

The file is present in the GIT tree and has been present since at least September 26th, 2014.

What is remarkable is that the file is not present in the latest 2.4.0 tar archive release.

Somebody needs to fix the creation of the release archive file to ensure that this file is included.

**Comment by uartie** [comment]
@XinfengZhang is this being resolved?  It should be trivial.

**Comment by XinfengZhang** [comment]
no, if ./configure with --enable-docs, still same issue reported. if you download the tarball from the release. when call make dist-bzip2 , this file is not included in the tarball
