### ISSUE TITLE
Stable Encoding Performance

### ISSUE THREAD

**Issue by zhoub** [intel/libva#311]
Hi !

I'd like to know is that possible to control the stability of the both encoding and decoding ? Because the encoding time is not stable that video streaming doesn't look well, is there any suggested configuration for this ? Thanks !

**Comment by XinfengZhang** [comment]
it should related with driver instead of libva.

**Comment by Entropy512** [comment]
By "stable" do you mean "consistent latency"?  That should be achievable using VBV/HRD and intra refresh, assuming the driver supports them.  (I'm in the process of trying to implement intra refresh support for libva in ffmpeg, it's not in there currently, in order to support a project that requires low-latency video transmission)

If by "stable" you mean "it crashes on your computer" - I can't really help you there as I'm unable to reproduce any problems.  At least for native English speakers, "unstable" software is software that crashes - but it sounds like this is not what you were asking?

**Comment by zhoub** [comment]
Sorry now the project is so busy that I can not spare time to debug for Intel. After a while.
