### ISSUE TITLE
libva error: /usr/lib/dri/i965_drv_video.so init failed

### ISSUE THREAD

**Issue by Vapstare1** [intel/libva#559]
I get this error when running vdpauinfo with environment variable set as VDPAU_DRIVER=va_gl. I am facing this issue on sway.

**Comment by XinfengZhang** [comment]
suppose you also are calling VAAPI :)

**Comment by Vapstare1** [comment]
> suppose you also are calling VAAPI :)

I dont understand what you mean

**Comment by XinfengZhang** [comment]
you call vdpauinfo , and set driver name to va_gl, it means vdpau will call libvdapu-va-gl.so, it will call libva, then libva will call i965, right? the call stack is long, and suppose it is not a libva issue, it is an issue with i965_video_drv.so, which is in here[https://github.com/intel/intel-vaapi-driver] . and also , you should check your environment, platform info. because i965 will not work from TGL ...
so, the issue description is too simple :)  , and should be reported in another place.

**Comment by Vapstare1** [comment]
ok thanks
